/* In-app manual and searchable operating guide. Source fragment; bundled by esbuild. */
  const DOMUS_MANUAL_SECTIONS = Object.freeze([
    { id: 'start', title: '1. První spuštění a bezpečné uložení', keywords: 'první spuštění instalace data lokální záloha', body: `<p>DOMUS je local-first aplikace: projektová data se ukládají na tomto zařízení. Začněte založením projektu, zkontrolujte úložiště a ještě před rozsáhlými úpravami vytvořte zálohu.</p><ol><li>Spusťte aplikaci přes <strong>Spustit-DOMUS-Studio.bat</strong>.</li><li>Založte projekt a vyberte šablonu.</li><li>V části <strong>Úložiště a obnova</strong> ověřte volnou kapacitu.</li><li>Pravidelně exportujte úplnou zálohu mimo počítač.</li></ol><div class="info-box warning"><strong>Důležité:</strong> fotografie a AI vizualizace mohou projekt výrazně zvětšit. Uchovávejte pouze užitečné výstupy a zálohujte je.</div>` },
    { id: 'workflow', title: '2. Doporučený pracovní postup', keywords: 'workflow postup projekt', body: `<ol><li><strong>Zaměření:</strong> zapište fyzicky ověřené rozměry a kritické instalační body.</li><li><strong>Fotografie:</strong> vložte celkový pohled a detaily.</li><li><strong>AI Studio:</strong> analyzujte snímky, vytvořte koncepční vizualizace nebo požádejte asistenta o návrh změn.</li><li><strong>Precision 2D:</strong> vytvořte přesnou geometrii, vrstvy a prvky.</li><li><strong>Materiály a rozpočet:</strong> nahraďte odhady konkrétními výrobky a nabídkami.</li><li><strong>DOMUS Verify:</strong> vyřešte kolize, neověřené rozměry a technická rizika.</li><li><strong>Poptávka a Report Studio:</strong> připravte podklad pro dodavatele.</li><li><strong>Deník a pasport:</strong> dokumentujte realizaci, skryté prvky a záruky.</li></ol>` },
    { id: 'field', title: '3. Zaměření skutečného stavu', keywords: 'měření zaměření lidar telefon rozměry', body: `<p>Každý rozměr má zdroj a míru jistoty. Za ověřený považujte pouze údaj skutečně změřený na místě.</p><ul><li>Zakládejte samostatná zaměření podle návštěvy nebo části stavby.</li><li>Měřte od pevných rohů, os a výškových úrovní.</li><li>Ke kritickému rozměru přiložte fotografii s měřítkem.</li><li>Import LiDAR/RoomPlan používejte jako podklad, ne jako automaticky přesný projekt.</li></ul>` },
    { id: 'photos', title: '4. Fotografie a anotace', keywords: 'fotografie kóta kalibrace', body: `<p>Na hlavní fotografii lze kreslit kóty a poznámky. Pro přesné měřítko nejprve označte známou vzdálenost a zadejte její skutečnou hodnotu.</p><ol><li>Nahrajte ostrý snímek bez digitálního zoomu.</li><li>Kalibrujte podle viditelného a fyzicky změřeného úseku.</li><li>Přidejte kóty a poznámky.</li><li>Pro AI Studio přidejte také čelní, boční a detailní pohledy.</li></ol>` },
    { id: 'ai-studio', title: '5. DOMUS AI Studio – přehled', keywords: 'ai studio vision vizualizátor asistent', body: `<p>AI Studio má tři režimy:</p><ul><li><strong>Analýza:</strong> rozpozná viditelné prvky, nejistoty a doporučená měření.</li><li><strong>Vizualizátor:</strong> upraví reálnou fotografii do koncepčního návrhu.</li><li><strong>Asistent:</strong> vede chat nad projektovými daty a připravuje potvrzované změny.</li></ul><div class="info-box"><strong>Společné pravidlo:</strong> AI výstup je návrh. Rozměry, proveditelnost, konstrukce a bezpečnost musí být ověřeny.</div>` },
    { id: 'ai-analysis', title: '6. AI analýza fotografií', keywords: 'analýza fotografie prvky půdorys', body: `<ol><li>Nahrajte 2–6 pohledů stejného prostoru.</li><li>Pojmenujte je a uveďte směr pohledu.</li><li>Nejprve spusťte lokální kontrolu kvality.</li><li>Cloudovou analýzu spusťte až po kontrole sdílených údajů.</li><li>Výsledek použijte jako seznam prvků a měření k ověření.</li><li>Půdorys vytvořte až po ručním potvrzení šířky, hloubky a výšky.</li></ol>` },
    { id: 'visualizer', title: '7. AI vizualizátor reálné fotografie', keywords: 'vizualizace obraz návrh před po', body: `<ol><li>Vyberte zdrojový snímek s co nejrovnější perspektivou.</li><li>Do hlavního zadání napište požadovaný výsledek.</li><li>Odděleně napište, co se musí zachovat, co odstranit a co přidat.</li><li>Rozpoznané dveře, okna či rozvody lze zamknout.</li><li>Vyberte styl, kvalitu, formát a počet návrhů.</li><li>Před odesláním zkontrolujte seznam sdílených dat.</li><li>Výsledky porovnejte posuvníkem a vybraný návrh přeneste do <strong>Před / po</strong>.</li></ol><div class="info-box warning"><strong>Omezení:</strong> vizualizace může změnit drobné proporce nebo vymyslet detail. Není podkladem pro objednávku ani montáž.</div>` },
    { id: 'ai-assistant', title: '8. Projektový AI asistent', keywords: 'chat změny potvrzení objekty materiály rozpočet', body: `<p>Asistent vidí strukturu aktivní varianty: 2D prvky, materiály, rozpočet, základní výměry a podle nastavení také poznámky či lokalitu.</p><ol><li>Napište konkrétní požadavek.</li><li>Asistent může pouze poradit, nebo připravit návrh akcí.</li><li>V pravém panelu zkontrolujte každou akci a předpoklady.</li><li>Teprve tlačítkem <strong>Potvrdit a provést</strong> se projekt změní.</li><li>Bezprostředně lze změnu vrátit tlačítkem Zpět.</li></ol><p>Podporované akce zahrnují přidání, posun, změnu rozměru a odstranění 2D prvku, doplnění materiálu či nákladu, změnu rezervy, poznámek, výšky stěn, povrchu a vytvoření nové varianty.</p>` },
    { id: 'plan', title: '9. Precision 2D', keywords: '2d půdorys vrstvy prvky stěny', body: `<ul><li>Nejdříve vytvořte uzavřený obrys stěn.</li><li>Nastavte správné měřítko a přesné délky.</li><li>Vkládejte prvky do odpovídajících vrstev.</li><li>Uzamkněte hotové vrstvy proti nechtěnému posunu.</li><li>U dveří nastavte stranu pantů a směr otevírání.</li><li>Každý AI vložený prvek ručně zkontrolujte.</li></ul>` },
    { id: 'materials', title: '10. Materiály, výrobky a knihovna', keywords: 'materiály výrobky knihovna odkaz', body: `<p>Materiály mohou být počítány ručně nebo z plochy podlahy, stěn, stropu či obvodu. Zadejte vydatnost a prořez. Import z odkazu je pomocný a všechny parametry je nutné ověřit na stránce výrobce.</p>` },
    { id: 'model', title: '11. Řez, 3D a prezentace', keywords: 'řez 3d vr model', body: `<p>3D model vychází z 2D geometrie, výšky stěn, prvků a přiřazených povrchů. Slouží ke kontrole prostorových vztahů a prezentaci, nikoli jako statický nebo výrobní model.</p>` },
    { id: 'budget', title: '12. Rozpočet', keywords: 'rozpočet dph rezerva náklady', body: `<p>Pořadí výpočtu je materiály + práce a ostatní náklady, následně rezerva, mezisoučet a DPH. Odhadované ceny vždy nahraďte konkrétními nabídkami. Rezervu přizpůsobte míře neznámých konstrukcí.</p>` },
    { id: 'verify', title: '13. DOMUS Verify', keywords: 'kontrola kolize rizika', body: `<p>Kontrola hledá kolize, neověřená měření, otevřený půdorys, odstupy instalací a prostor pro dveře. Nález označte jako vyřešený až po skutečné změně nebo doloženém ověření. Přijaté riziko vyžaduje zdůvodnění.</p>` },
    { id: 'delivery', title: '14. Poptávka, report a realizace', keywords: 'poptávka report deník pasport záruka', body: `<p>Poptávka má jasně uvést rozsah, výjimky, otázky a požadovaný způsob odpovědi. Report Studio sestaví projektový balík. Během realizace ukládejte fotografie před zakrytím, skutečné náklady, změny a doklady k zárukám.</p>` },
    { id: 'ai-setup', title: '15. Nastavení AI, soukromí a náklady', keywords: 'api klíč soukromí cena nastavení', body: `<ol><li>Spusťte <strong>Nastavit-AI-pripojeni.bat</strong>.</li><li>Vložte vlastní OpenAI API klíč.</li><li>Ponechte doporučený textový a obrazový model, pokud nemáte konkrétní důvod je měnit.</li><li>Klíč se ukládá šifrovaně mimo webovou složku a neposílá se do projektu ani zálohy.</li><li>Každé cloudové odeslání potvrďte a zkontrolujte přepínače sdílení.</li></ol><div class="info-box warning"><strong>Náklady:</strong> API spotřeba se účtuje na vašem API účtu. Obrazové generování je zpravidla náročnější než textová odpověď.</div>` },
    { id: 'backup', title: '16. Zálohy a synchronizace', keywords: 'záloha synchronizace telefon notebook', body: `<p>Úplná záloha obsahuje projekty i přílohy a kontroluje integritu. Mobilní synchronizace funguje pouze v důvěryhodné místní síti, s jednorázovým párovacím kódem a následným tokenem. Před nahrazením projektu z jiného zařízení vytvořte zálohu.</p>` },
    { id: 'troubleshooting', title: '17. Řešení problémů', keywords: 'chyba nefunguje problém', body: `<ul><li><strong>AI není dostupná:</strong> spusťte aplikaci hlavním BAT souborem, ověřte klíč a internet.</li><li><strong>Fotografie je příliš velká:</strong> aplikace ji při importu zmenšuje; staré nepotřebné vizualizace odstraňte.</li><li><strong>3D se nezobrazí:</strong> obnovte kartu, zkontrolujte WebGL a spusťte diagnostiku.</li><li><strong>Data chybí:</strong> otevřete Úložiště a obnova, koš nebo poslední bod obnovy.</li><li><strong>Výsledek AI je chybný:</strong> nepoužívejte jej; zpřesněte zadání a explicitně zamkněte neměnné prvky.</li></ul>` },
  ]);

  function renderManualTab(project, variant) {
    const query = String(state.manualSearch || '').trim().toLowerCase();
    const sections = DOMUS_MANUAL_SECTIONS.filter((section) => !query || `${section.title} ${section.keywords} ${section.body.replace(/<[^>]+>/g, ' ')}`.toLowerCase().includes(query));
    return `<div class="manual-workspace"><section class="panel manual-hero"><div class="panel-head"><div><p class="eyebrow">DOMUS Studio Premium v7.3</p><h2>Kompletní pracovní manuál</h2><p>Praktický návod od prvního zaměření až po AI vizualizaci, 2D/3D návrh, rozpočet, realizaci a zálohu.</p></div><div class="panel-actions"><button class="btn btn-secondary" data-action="open-manual-document">Otevřít samostatný manuál</button></div></div><div class="manual-search"><input id="manualSearch" type="search" value="${escapeHtml(state.manualSearch || '')}" placeholder="Hledat v manuálu…" aria-label="Hledat v manuálu"><span id="manualFilterCount">${sections.length} kapitol</span></div></section><div id="manualResults" data-render-region="manual" class="manual-results">${sections.length ? sections.map((section, index) => `<details class="manual-section" id="manual-${section.id}" ${!query && index === 0 ? 'open' : query ? 'open' : ''}><summary><span>${escapeHtml(section.title)}</span><small>Rozbalit kapitolu</small></summary><div class="manual-section-body">${section.body}</div></details>`).join('') : '<div class="empty-state"><strong>Nic nenalezeno</strong><p>Zkuste obecnější výraz, například „AI“, „rozpočet“ nebo „záloha“.</p></div>'}</div></div>`;
  }

  function openManualSection(section) {
    state.currentTab = 'manual'; state.manualSearch = ''; render();
    requestAnimationFrame(() => { const details = document.getElementById(`manual-${section}`); if (details) { details.open = true; details.scrollIntoView({ behavior: state.uiPreferences?.reduceMotion ? 'auto' : 'smooth', block: 'start' }); } });
  }

  function openManualDocument() { window.open('./MANUAL-DOMUS-STUDIO-v7.3.html', '_blank', 'noopener,noreferrer'); }
