/* DOMUS Studio Premium Core v7: DXF, conflict-aware merge, performance budgets and release metadata. */
(() => {
  'use strict';
  const RELEASE = Object.freeze({ version: '7.0.0', schemaVersion: 7, channel: 'premium', architecture: 'modular-local-first' });
  const clone = (value) => JSON.parse(JSON.stringify(value));
  const finite = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
  const isoTime = (value) => { const time = Date.parse(value || ''); return Number.isFinite(time) ? time : 0; };
  const safeText = (value) => String(value ?? '').replace(/[\r\n]+/g, ' ').slice(0, 240);
  function fnv1a(text) { let hash = 2166136261; for (let i = 0; i < text.length; i += 1) { hash ^= text.charCodeAt(i); hash = Math.imul(hash, 16777619); } return (hash >>> 0).toString(16).padStart(8, '0'); }
  function line(layer,x1,y1,x2,y2){return `0\nLINE\n8\n${safeText(layer)}\n10\n${x1}\n20\n${-y1}\n30\n0\n11\n${x2}\n21\n${-y2}\n31\n0\n`;}
  function poly(layer,points){let out=`0\nLWPOLYLINE\n8\n${safeText(layer)}\n90\n${points.length}\n70\n1\n`;points.forEach(([x,y])=>{out+=`10\n${x}\n20\n${-y}\n`;});return out;}
  function circle(layer,x,y,r){return `0\nCIRCLE\n8\n${safeText(layer)}\n10\n${x}\n20\n${-y}\n30\n0\n40\n${r}\n`;}
  function text(layer,x,y,height,value){return `0\nTEXT\n8\n${safeText(layer)}\n10\n${x}\n20\n${-y}\n30\n0\n40\n${height}\n1\n${safeText(value)}\n`;}
  function exportDxf(plan,meta={}){
    if(!plan||!Array.isArray(plan.walls)||!Array.isArray(plan.objects))throw new Error('Výkres není platný.');
    const scale=Math.max(.001,finite(plan.scale,50)); const mm=(px)=>Math.round((finite(px)/scale)*1000*1000)/1000; let entities='';
    plan.walls.forEach((wall,index)=>{entities+=line('DOMUS_WALLS',mm(wall.x1),mm(wall.y1),mm(wall.x2),mm(wall.y2));entities+=text('DOMUS_DIMENSIONS',mm((wall.x1+wall.x2)/2),mm((wall.y1+wall.y2)/2),120,`S${index+1} ${(Math.hypot(wall.x2-wall.x1,wall.y2-wall.y1)/scale).toFixed(3)} m`);});
    plan.objects.forEach((object)=>{const layerName=`DOMUS_${String(object.layer||'OBJECTS').toUpperCase().replace(/[^A-Z0-9_]/g,'_')}`;const x=mm(object.x),y=mm(object.y),w=Math.max(1,mm(object.width)),d=Math.max(1,mm(object.depth));entities+=(object.shape==='circle'||object.shape==='oval')?circle(layerName,x+w/2,y+d/2,Math.max(1,Math.min(w,d)/2)):poly(layerName,[[x,y],[x+w,y],[x+w,y+d],[x,y+d]]);entities+=text('DOMUS_LABELS',x,y-120,100,object.type||'Prvek');});
    return `999\nDOMUS Studio ${RELEASE.version} - ${safeText(meta.projectName||'Projekt')} / ${safeText(meta.variantName||'Varianta')}\n0\nSECTION\n2\nHEADER\n9\n$ACADVER\n1\nAC1015\n9\n$INSUNITS\n70\n4\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n${entities}0\nENDSEC\n0\nEOF\n`;
  }
  function keyedMerge(localItems=[],remoteItems=[],path=''){
    const localMap=new Map(localItems.map(item=>[item.id,item])),remoteMap=new Map(remoteItems.map(item=>[item.id,item]));const merged=[],conflicts=[];
    new Set([...localMap.keys(),...remoteMap.keys()]).forEach((id)=>{const local=localMap.get(id),remote=remoteMap.get(id);if(!local)return merged.push(clone(remote));if(!remote)return merged.push(clone(local));const lh=fnv1a(JSON.stringify(local)),rh=fnv1a(JSON.stringify(remote));if(lh===rh)return merged.push(clone(local));const winner=isoTime(remote.updatedAt||remote.createdAt)>isoTime(local.updatedAt||local.createdAt)?remote:local;conflicts.push({path:`${path}/${id}`,id,chosen:winner===remote?'remote':'local',local:clone(local),remote:clone(remote)});merged.push(clone(winner));});return{merged,conflicts};
  }
  function mergeVariant(local,remote,path){const merged={...clone(local),...clone(remote)},conflicts=[];for(const key of ['materials']){const r=keyedMerge(local[key]||[],remote[key]||[],`${path}/${key}`);merged[key]=r.merged;conflicts.push(...r.conflicts);}const costs=keyedMerge(local.costs?.lines||[],remote.costs?.lines||[],`${path}/costs`);merged.costs={...clone(local.costs||{}),...clone(remote.costs||{}),lines:costs.merged};conflicts.push(...costs.conflicts);const walls=keyedMerge(local.plan?.walls||[],remote.plan?.walls||[],`${path}/plan/walls`),objects=keyedMerge(local.plan?.objects||[],remote.plan?.objects||[],`${path}/plan/objects`);merged.plan={...clone(local.plan||{}),...clone(remote.plan||{}),walls:walls.merged,objects:objects.merged,layerVisibility:{...(local.plan?.layerVisibility||{}),...(remote.plan?.layerVisibility||{})},layerLocks:{...(local.plan?.layerLocks||{}),...(remote.plan?.layerLocks||{})}};conflicts.push(...walls.conflicts,...objects.conflicts);return{merged,conflicts};}
  function mergeProjects(localProject,remoteProject){
    if(!localProject)return{project:clone(remoteProject),conflicts:[],summary:{added:1,resolved:0}};if(!remoteProject)return{project:clone(localProject),conflicts:[],summary:{added:0,resolved:0}};if(localProject.id!==remoteProject.id)throw new Error('Nelze sloučit projekty s různým ID.');
    const project={...clone(localProject),...clone(remoteProject)},conflicts=[],lm=new Map((localProject.variants||[]).map(x=>[x.id,x])),rm=new Map((remoteProject.variants||[]).map(x=>[x.id,x]));project.variants=[];new Set([...lm.keys(),...rm.keys()]).forEach(id=>{const l=lm.get(id),r=rm.get(id);if(!l)return project.variants.push(clone(r));if(!r)return project.variants.push(clone(l));const result=mergeVariant(l,r,`/variants/${id}`);project.variants.push(result.merged);conflicts.push(...result.conflicts);});
    const sl=localProject.survey||{},sr=remoteProject.survey||{};project.survey={...clone(sl),...clone(sr)};const sessions=keyedMerge(sl.field?.sessions||[],sr.field?.sessions||[],'/survey/field/sessions');project.survey.field={...clone(sl.field||{}),...clone(sr.field||{}),sessions:sessions.merged};conflicts.push(...sessions.conflicts);const annotations=keyedMerge(sl.photo?.annotations||[],sr.photo?.annotations||[],'/survey/photo/annotations');project.survey.photo={...clone(sl.photo||{}),...clone(sr.photo||{}),annotations:annotations.merged};conflicts.push(...annotations.conflicts);
    const ll=localProject.lifecycle||{},lr=remoteProject.lifecycle||{};project.lifecycle={...clone(ll),...clone(lr)};for(const key of ['entries','warranties','passport']){const result=keyedMerge(ll[key]||[],lr[key]||[],`/lifecycle/${key}`);project.lifecycle[key]=result.merged;conflicts.push(...result.conflicts);}project.updatedAt=new Date(Math.max(Date.now(),isoTime(localProject.updatedAt),isoTime(remoteProject.updatedAt))).toISOString();project.syncMerge={at:new Date().toISOString(),conflicts:conflicts.map(({local,remote,...rest})=>rest)};return{project,conflicts,summary:{variants:project.variants.length,resolved:conflicts.length}};
  }
  function complexity(project){const variants=project?.variants||[];const totals=variants.reduce((acc,v)=>{acc.walls+=v.plan?.walls?.length||0;acc.objects+=v.plan?.objects?.length||0;acc.materials+=v.materials?.length||0;acc.photos+=(v.ai?.photoSet?.length||0)+(v.field?.sessions||[]).reduce((sum,s)=>sum+(s.photos?.length||0),0);return acc;},{walls:0,objects:0,materials:0,photos:0});const score=totals.walls+totals.objects*1.5+totals.materials*.6+totals.photos*2;return{...totals,variants:variants.length,score:Math.round(score),level:score>1500?'extreme':score>600?'large':score>200?'medium':'small',workerRecommended:score>400};}
  function warrantyIcs(project){const rows=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//DOMUS Studio//Warranty reminders//CS'];(project?.lifecycle?.warranties||[]).forEach(item=>{if(!item.purchaseDate||!finite(item.warrantyMonths))return;const end=new Date(`${item.purchaseDate}T12:00:00`);end.setMonth(end.getMonth()+finite(item.warrantyMonths));rows.push('BEGIN:VEVENT',`UID:${safeText(item.id||fnv1a(JSON.stringify(item)))}@domus-studio`,`DTSTART;VALUE=DATE:${end.toISOString().slice(0,10).replaceAll('-','')}`,`SUMMARY:Konec záruky – ${safeText(item.item||'položka')}`,'BEGIN:VALARM','TRIGGER:-P30D','ACTION:DISPLAY','DESCRIPTION:Záruka skončí za 30 dní','END:VALARM','END:VEVENT');});rows.push('END:VCALENDAR');return `${rows.join('\r\n')}\r\n`;}
  window.DomusPremium=Object.freeze({RELEASE,exportDxf,mergeProjects,complexity,warrantyIcs,fnv1a});
})();
